tasks:
  - name: Install Dependencies
    init: |
      pnpm install --frozen-lockfile
      pnpm --filter @apps/test prisma:generate
    command: |
      gp sync-done setup

  - name: Set WakaTime API Key
    command: |
      echo -e "[settings]\napi_key = $WAKATIME_API_KEY" > ~/.wakatime.cfg
      source ~/.bashrc

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - kamikillerto.vscode-colorize
    - IronGeek.vscode-env
    - eamodio.gitlens
    - wix.vscode-import-cost
    - oderwat.indent-rainbow
    - kimlimjustin.jsdoc-generator
    - shd101wyy.markdown-preview-enhanced
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - Prisma.prisma
    - bradlc.vscode-tailwindcss
    - WakaTime.vscode-wakatime
    - formulahendry.auto-rename-tag
    - aaron-bond.better-comments
    - adpyke.codesnap
    - fabiospampinato.vscode-todo-plus
    - Gruntfuggly.todo-tree
