name: PR Checks

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.ref }}'

jobs:
  code-quality:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, prettier, tsc]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm --filter @apps/test prisma:generate

      - name: ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm --filter @apps/test prisma:generate

      - name: Run unit tests
        run: pnpm run test
