name: PR Checks

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.ref }}'

jobs:
  code-quality:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, prettier, tsc]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm --filter @apps/test prisma:generate

      - name: Run unit tests
        run: pnpm run test

  build-libraries:
    name: Build libraries and upload artifacts
    runs-on: ubuntu-latest
    needs: [code-quality, unit-tests]
    strategy:
      fail-fast: false
      matrix:
        lib: ['iron-auth', '@iron-auth/kysely-adapter', '@iron-auth/react']
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set outputs
        id: info
        run: |
          echo "lib_name=${{ matrix.lib }}" >> $GITHUB_OUTPUT
          echo "lib_path=${{ matrix.lib }}" | sed "s/\@iron\-auth\///g" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Alter package.json versions
        run: bash ./scripts/alter-version libs/${{ steps.info.outputs.lib_path  }} ${{ steps.hash.outputs.sha_short }} PR=${{ github.event.number }}

      - name: Build
        run: pnpm run build --filter=${{ steps.info.outputs.lib_name }}

      - name: Package for release
        if: ${{ github.repository_owner == 'iron-auth' && github.event_name == 'pull_request' }}
        run: |
          cd libs/${{ steps.info.outputs.lib_path }}/dist
          pnpm pack
          cd ../../..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        if: ${{ github.repository_owner == 'iron-auth' && github.event_name == 'pull_request' }}
        with:
          name: npm-package-${{ steps.info.outputs.lib_name }}-${{ github.event.number }}
          path: libs/${{ steps.info.outputs.lib_path }}/dist/${{ steps.info.outputs.lib_name }}-*.tgz

  prerelease-comment:
    name: Create prerelease comment
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'iron-auth' && github.event_name == 'pull_request' }}
    needs: [build-libraries]
    strategy:
      fail-fast: false
      matrix:
        lib: [iron-auth, '@iron-auth/kysely-adapter', '@iron-auth/react']
    steps:
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.number }}
          message: |
            Prereleases are available for testing.

            | Library                   | Download Link |
            |---------------------------|---------------|
            | iron-auth                 | `https://prerelease-registry.ixion-labs.workers.dev/iron-auth/iron-auth/runs/${{ github.run_id }}/npm-package-iron-auth-${{ github.event.number }}` |
            | @iron-auth/kysely-adapter | `https://prerelease-registry.ixion-labs.workers.dev/iron-auth/iron-auth/runs/${{ github.run_id }}/npm-package-@iron-auth/kysely-adapter-${{ github.event.number }}` |
            | @iron-auth/react          | `https://prerelease-registry.ixion-labs.workers.dev/iron-auth/iron-auth/runs/${{ github.run_id }}/npm-package-@iron-auth/react-${{ github.event.number }}` |
